### ISSUE TITLE
No routes found. If you are using a custom src/routes directory, make sure it is specified in svelte.config.js

### ISSUE THREAD

**Issue by Exey** [roboteam-digital/telegram-json-ui#11]
Windows 10 node v18.16.0

> No routes found. If you are using a custom src/routes directory, make sure it is specified in svelte.config.js
    at create_routes_and_nodes (file:///D:/Telegrams/telegram-json-ui/frontend/sveltekit/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:313:11)
    at create_manifest_data (file:///D:/Telegrams/telegram-json-ui/frontend/sveltekit/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:25:28)
    at Module.all_types (file:///D:/Telegrams/telegram-json-ui/frontend/sveltekit/node_modules/@sveltejs/kit/src/core/sync/sync.js:68:24)
    at file:///D:/Telegrams/telegram-json-ui/frontend/sveltekit/node_modules/@sveltejs/kit/src/cli.js:38:15
npm ERR! code 1
npm ERR! path D:\Telegrams\telegram-json-ui\frontend\sveltekit
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c svelte-kit sync

macOS 13.0.1 node v19.7.0

> No routes found. If you are using a custom src/routes directory, make sure it is specified in svelte.config.js
    at create_routes_and_nodes (file:///Users/exey/Documents/telegram-json-ui/frontend/sveltekit/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:313:11)
    at create_manifest_data (file:///Users/exey/Documents/telegram-json-ui/frontend/sveltekit/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:25:28)
    at Module.all_types (file:///Users/exey/Documents/telegram-json-ui/frontend/sveltekit/node_modules/@sveltejs/kit/src/core/sync/sync.js:68:24)
    at file:///Users/exey/Documents/telegram-json-ui/frontend/sveltekit/node_modules/@sveltejs/kit/src/cli.js:38:15
npm ERR! code 1
npm ERR! path /Users/exey/Documents/telegram-json-ui/frontend/sveltekit
npm ERR! command failed
npm ERR! command sh -c svelte-kit sync

**Comment by alexander-mart** [comment]
@Exey It's because SvelteKit v1.0 breaking changes. I will patch `package.json` when i can, or you can do it.
